language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - pip install coveralls
# command to run tests
script:
  - coverage run -m doctest -v tuples.rst
  - coverage run -m doctest -v functions.rst
after_success:
  - coveralls
